<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="0" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-19T13:25:03 EST" name="Suite" finished-at="2023-01-19T13:25:54 EST" duration-ms="51321">
    <groups>
    </groups>
    <test started-at="2023-01-19T13:25:03 EST" name="Test" finished-at="2023-01-19T13:25:54 EST" duration-ms="51321">
      <class name="com.naveenautomation.Tests.AccountCreatedTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.naveenautomation.Tests.AccountCreatedTest@4d1bf319]" started-at="2023-01-19T13:25:03 EST" name="setUp" finished-at="2023-01-19T13:25:07 EST" duration-ms="4181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="verifyUserIsAbleToSignUpSuccesfully()[pri:0, instance:com.naveenautomation.Tests.AccountCreatedTest@4d1bf319]" started-at="2023-01-19T13:25:07 EST" name="verifyUserIsAbleToSignUpSuccesfully" finished-at="2023-01-19T13:25:10 EST" duration-ms="2066" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Sign up failed expected [Your Account Has Been Created!] but found [Register Account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Sign up failed expected [Your Account Has Been Created!] but found [Register Account]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.naveenautomation.Tests.AccountCreatedTest.verifyUserIsAbleToSignUpSuccesfully(AccountCreatedTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserIsAbleToSignUpSuccesfully -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.naveenautomation.Tests.AccountCreatedTest@4d1bf319]" started-at="2023-01-19T13:25:10 EST" name="tearDown" finished-at="2023-01-19T13:25:26 EST" duration-ms="16298" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.naveenautomation.Tests.AccountCreatedTest@4d1bf319]" started-at="2023-01-19T13:25:26 EST" name="setUp" finished-at="2023-01-19T13:25:30 EST" duration-ms="4261" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="verifyUserIsAbleToSignUpSuccesfully()[pri:0, instance:com.naveenautomation.Tests.AccountCreatedTest@4d1bf319]" started-at="2023-01-19T13:25:30 EST" name="verifyUserIsAbleToSignUpSuccesfully" finished-at="2023-01-19T13:25:32 EST" duration-ms="2017" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Sign up failed expected [Your Account Has Been Created!] but found [Register Account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Sign up failed expected [Your Account Has Been Created!] but found [Register Account]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.naveenautomation.Tests.AccountCreatedTest.verifyUserIsAbleToSignUpSuccesfully(AccountCreatedTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserIsAbleToSignUpSuccesfully -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.naveenautomation.Tests.AccountCreatedTest@4d1bf319]" started-at="2023-01-19T13:25:32 EST" name="tearDown" finished-at="2023-01-19T13:25:48 EST" duration-ms="16285" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.naveenautomation.Tests.AccountCreatedTest@4d1bf319]" started-at="2023-01-19T13:25:48 EST" name="setUp" finished-at="2023-01-19T13:25:52 EST" duration-ms="4073" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUserIsAbleToSignUpSuccesfully()[pri:0, instance:com.naveenautomation.Tests.AccountCreatedTest@4d1bf319]" started-at="2023-01-19T13:25:52 EST" name="verifyUserIsAbleToSignUpSuccesfully" finished-at="2023-01-19T13:25:54 EST" duration-ms="1770" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Sign up failed expected [Your Account Has Been Created!] but found [Register Account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Sign up failed expected [Your Account Has Been Created!] but found [Register Account]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.naveenautomation.Tests.AccountCreatedTest.verifyUserIsAbleToSignUpSuccesfully(AccountCreatedTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserIsAbleToSignUpSuccesfully -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.naveenautomation.Tests.AccountCreatedTest@4d1bf319]" started-at="2023-01-19T13:25:54 EST" name="tearDown" finished-at="2023-01-19T13:25:54 EST" duration-ms="46" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.naveenautomation.Tests.AccountCreatedTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
